GET http://localhost/newsPub/index.php HTTP/1.1

###
GET https://example.com/comments
    ?page=2
    &pageSize=10
###
GET http://localhost/newsPub/index.php HTTP/1.1

###

POST http://localhost/newsPub/index.php HTTP/1.1
Content-Type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2019 18:27:50  GMT"
}